FROM jenkins/jenkins:latest
USER jenkins

WORKDIR /usr/src/
COPY jenkins-cli.jar .

#RUN <<EOF
#CMD cat /var/lib/jenkins/secrets/initialAdminPassword
#EOF

#/var/jenkins_home/secrets/initialAdminPassword
    # pwd
    # ls

# java -jar jenkins-cli.jar -s http://localhost:8080/ -auth admin:18f1d66675154135b43138851b23d84f help
